name: calibcam
channels:
  - defaults
dependencies:
  - python=3.6
  - matplotlib=3.1.3
  - numpy
  - opencv
  - py-opencv
  - pyyaml
  - scipy
  - pip
  - imageio
  - pyqt
  - pip:
    - bbo-ccvtools
    - autograd
