name: calibcam
channels:
  - defaults
dependencies:
  - python=3.6
  - matplotlib
  - numpy
  - opencv
  - py-opencv
  - pyyaml
  - scipy
  - pip
  - imageio
  - pip:
    - bbo-ccvtools
    - pyqt5
    - autograd
