name: calibcam
channels:
  - defaults
dependencies:
  - python=3.6
  - matplotlib
  - numpy
  - opencv
  - py-opencv
  - pyqt=5.9.7
  - pyyaml
  - qt=5.9.7
  - scipy
  - pip
  - pip:
    - bbo-ccvtools
    - autograd
