name: calibcam
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - opencv
  - py-opencv
  - pyyaml
  - scipy
  - imageio
  - joblib
  - cudatoolkit
  - pip
  - pip:
    - jaxlib
    - jax
    - bbo-ccvtools
    - bbo-calibcamlib
    - bbo-calibcam
