name: calibcam-2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - opencv
  - py-opencv
  - pyyaml
  - scipy
  - pip
  - imageio
  - pyqt
  - joblib
  - jax
  - pip:
    - bbo-ccvtools
    - bbo-calibcamlib
    - autograd
